### ISSUE TITLE
java.lang.NoClassDefFoundError: org/junit/runners/ParentRunner

### ISSUE THREAD

**Issue by a-k-khurana** [serenity-bdd/serenity-junit-screenplay-starter#10]
Below is my configuration. Getting java.lang.NoClassDefFoundError: org/junit/runners/ParentRunner when running tests.

ext {
    slf4jVersion = '1.7.7'
    serenityCoreVersion = '3.9.8'
    serenityCucumberVersion = '3.9.8'
    serenityRestAssuredVersion = '3.9.8'
    junitVersion = '4.12'
    assertJVersion = '3.8.0'
    logbackVersion = '1.2.3'
}

dependencies {
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.11.1'
    testImplementation group: 'org.apache.maven.plugins', name: 'maven-failsafe-plugin', version: '3.0.0-M5'
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation group: 'net.serenity-bdd', name: 'serenity-rest-assured', version: '3.9.8'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.10'
    implementation 'org.postgresql:postgresql:42.2.5'
    implementation group: 'org.postgresql', name: 'postgresql', version: '9.3-1100-jdbc4'
    implementation 'com.adyen:adyen-java-api-library:9.0.0'
    implementation group: 'org.json', name: 'json', version: '20210307'
    testImplementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-cucumber:${serenityCucumberVersion}",
            "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}",
            "org.assertj:assertj-core:${assertJVersion}"
    testImplementation 'com.auth0:java-jwt:4.0.0'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.13.0'
    testImplementation 'org.junit.platform:junit-platform-suite:1.10.0-M1'
    testImplementation 'net.serenity-bdd:serenity-junit5:3.9.8'
    // https://mvnrepository.com/artifact/net.serenity-bdd/serenity-model
    implementation 'net.serenity-bdd:serenity-model:3.9.8'
    testImplementation 'net.serenity-bdd:serenity-junit5:3.9.8'
}

**Comment by a-k-khurana** [comment]
java.lang.NoClassDefFoundError: org/junit/runners/ParentRunner
        at io.cucumber.core.plugin.SerenityReporterParallel.getCucumberRuntimeTags(SerenityReporterParallel.java:613)
        at io.cucumber.core.plugin.SerenityReporterParallel.testRunHasFilterTags(SerenityReporterParallel.java:608)
        at io.cucumber.core.plugin.SerenityReporterParallel.examplesAreNotExcludedByTags(SerenityReporterParallel.java:594)
        at io.cucumber.core.plugin.SerenityReporterParallel.handleExamples(SerenityReporterParallel.java:539)
        at io.cucumber.core.plugin.SerenityReporterParallel.handleTestCaseStarted(SerenityReporterParallel.java:277)

**Comment by a-k-khurana** [comment]
If I included junit4 as dependency, it fixes it, but parallel processing stops working.

**Comment by a-k-khurana** [comment]
is it possible for you provide me what depdencies are supported with serenity 3.9.8?

**Comment by a-k-khurana** [comment]
we are currently on version 3.8.1, and upgrading to 3.9.8 just because while reports are generating some of the report html files are missing. Are you aware of any such issue, and if yes, which version is that fixed in
